version: '3.3'

services:
  backend:
    image: unicef/rapidsms-website:latest
    environment:
      DJANGO_SETTINGS_MODULE: 'website.settings'
      DATABASE_URL: psql://postgres:pass@db:5432/postgres
      DEBUG: 'true'
      CSRF_COOKIE_SECURE: ''
      SECURE_SSL_REDIRECT: ''
      SESSION_COOKIE_HTTPONLY: ''
      SESSION_COOKIE_SECURE: ''
      #PROJECT_ROOT: '/var/www/rapidpro_community_portal/'
      COMPRESS_ENABLED: 'true'
      SECRET_KEY: 'top-secret'
    command: uwsgi
    ports:
     - "8000:8000"
    volumes:
      - "./src:/code"
      - "./volumes/backend/var/rapidsms/:/var/rapidsms"
    depends_on:
      - db
      - redis
    container_name: rapidsms_website
    labels:
      - traefik.backend=backend
      - traefik.frontend.rule=PathPrefix:/
      - traefik.priority=1
      - traefik.enable=true
      - traefik.port=8000

  proxy:
    image: traefik:v1.7
    command: --api --docker
    ports:
      - "8082:80"
      - "8080:8080"
    container_name: rapidsms_website_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: website_production
    volumes:
      - "./volumes/db2/data:/var/lib/postgresql/data"
    container_name: rapidsms_website_db

  redis:
    image: redis
    container_name: rapidsms_website_redis
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
