# Generated by Django 2.2.9 on 2020-01-14 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('topo', models.TextField(blank=True, editable=False)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('scale', models.FloatField(default=0)),
                ('color', models.CharField(default='#EDDC4E', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topo', models.TextField(blank=True)),
                ('color', models.CharField(default='#EDDC4E', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
                ('topo', models.TextField(blank=True, editable=False)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('radius', models.PositiveIntegerField(default=10)),
                ('color', models.CharField(default='#EDDC4E', max_length=8)),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamaps.Scope')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
