# Generated by Django 2.2.9 on 2020-01-14 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomy', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pypi_updated', models.DateTimeField(blank=True, null=True, verbose_name='PyPI Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Flagged')),
                ('pkg_type', models.CharField(choices=[('A', 'Application'), ('B', 'Backend'), ('L', 'Library'), ('R', 'Router')], default='A', max_length=1, verbose_name='Package Type')),
                ('name', models.CharField(help_text='The name of the package on PyPI.', max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('tests_url', models.URLField(blank=True, help_text="Link to the package's public CI server, e.g. <a href='https://travis-ci.org/rapidsms/rapidsms'>https://travis-ci.org/rapidsms/rapidsms</a>.", null=True, verbose_name='CI/Tests')),
                ('repo_url', models.URLField(blank=True, help_text="The package's source code repository, e.g. <a href='https://github.com/rapidsms/rapidsms'>https://github.com/rapidsms/rapidsms</a>.", null=True, verbose_name='Source Code')),
                ('pypi_json', models.TextField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('maintainer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('maintainer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('version', models.CharField(blank=True, max_length=32, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=128, null=True)),
                ('docs_url', models.URLField(blank=True, help_text="Where the package's documentation is hosted, e.g. <a href='http://rapidsms.readthedocs.org/'>http://rapidsms.readthedocs.org</a>.", null=True, verbose_name='Documentation')),
                ('home_url', models.URLField(blank=True, help_text="The project's home page, e.g. <a href='http://rapidsms.org'>http://rapidsms.org</a>.", null=True, verbose_name='Home Page')),
                ('creator', models.ForeignKey(help_text='The creator of this content, who may or may not be its author.', on_delete=django.db.models.deletion.CASCADE, related_name='created_packages', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='packages', to='taxonomy.Taxonomy', verbose_name='Taxonomy')),
            ],
            options={
                'ordering': ['-release_date', '-updated'],
            },
        ),
    ]
