# Generated by Django 2.2.9 on 2020-01-14 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datamaps', '__first__'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.CharField(choices=[('I', 'Individual'), ('O', 'Organization')], default='I', max_length=1, verbose_name='Account Type')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('display_email', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Website URL')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Github URL')),
                ('gravatar_email', models.EmailField(blank=True, help_text='If supplied,  RapidSMS.org will use your Gravatar.', max_length=254, null=True, verbose_name='Gravatar Email Address (private)')),
                ('avatar', models.ImageField(blank=True, help_text='Upload a profile or company logo image if you do not have or want to use your Gravatar.', null=True, upload_to='images/avatars')),
                ('for_hire', models.BooleanField(default=False, verbose_name='Are you available for RapidSMS-related hire or consulting?')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether this user can log into the admin site.', verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamaps.Country')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
