# Generated by Django 2.2.11 on 2020-03-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL([("ALTER TABLE users_user ALTER COLUMN last_login DROP NOT NULL")])
    ]
